"""
Fixed, deterministic remediation templates - one per MVP incident type.

These are intentionally NOT generated by the LLM: Bedrock only writes the
human-readable diagnosis (see bedrock_client.py). The actual action taken
after human approval always comes from this table, so behavior is safe and
predictable. Once approved, the executor doesn't just run these steps once -
it keeps re-checking the real underlying condition (available replicas,
endpoint addresses, node Ready, etc.) on an interval and retries until it
actually clears or a bounded retry budget runs out (see executor.py).
"""
from __future__ import annotations

TEMPLATES: dict[str, dict] = {
    "crashloop": {
        "title": "Restart crash-looping pod (rollback bad config if present)",
        "steps": [
            "Inspect recent container logs (Loki panel) for the crash reason.",
            "If the Deployment template was changed to a broken command/config, revert it to the last-known-good version.",
            "Delete the crash-looping pod so the ReplicaSet reschedules a fresh replica.",
            "Keep checking until the Deployment has all replicas Available and no pod is still crash-looping.",
        ],
        "action": "delete_pod",
    },
    "node_not_ready": {
        "title": "Cordon node and wait for kubelet to recover",
        "steps": [
            "Cordon the node so no new pods are scheduled onto it while it is unhealthy.",
            "Keep polling the node's Ready condition on an interval (up to the retry budget).",
            "A node whose own kubelet is down cannot run a Kubernetes-scheduled fix "
            "(nothing can start on it until kubelet is back) - kubelet must be restarted "
            "out-of-band (in this kind demo: injector/node_not_ready.py --revert).",
            "As soon as it reports Ready, uncordon the node so scheduling resumes.",
        ],
        "action": "recover_node",
    },
    "service_unreachable": {
        "title": "Restore Service endpoints",
        "steps": [
            "Verify the Service selector matches the labels on the intended pods.",
            "Restore the Service's selector to the last-known-good value.",
            "Keep checking until the Endpoints object lists at least one healthy address.",
        ],
        "action": "fix_service_selector",
    },
    "networkpolicy_block": {
        "title": "Remove blocking NetworkPolicy",
        "steps": [
            "Identify NetworkPolicy objects in the namespace that could deny this traffic.",
            "Delete the offending NetworkPolicy (injected policies are labelled chaos=injected).",
            "Keep checking until no chaos=injected NetworkPolicy remains in the namespace.",
        ],
        "action": "delete_blocking_networkpolicy",
    },
    "replica_mismatch": {
        "title": "Rollback bad image/config and restart Deployment rollout",
        "steps": [
            "Check the Deployment's pod template for a bad image/config causing failures.",
            "Restore the last-known-good image if one was recorded.",
            "Trigger a rollout restart to force fresh ReplicaSet pods.",
            "Keep checking until status.availableReplicas matches spec.replicas.",
        ],
        "action": "rollout_restart_deployment",
    },
}
